backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:  
  - name: "stories"
    label: "Stories"
    folder: "/content/stories"
    create: true
    publish: false
    delete: false
    slug: "{{slug}}"
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'body'
        label: 'Body'
        widget: 'markdown' 
        hint: 'enter story here'
      - name: 'author'
        label: 'Author'
        widget: 'hidden'
        default: "a teacher"
      - name: 'level'
        label: 'Level'
        widget: 'select'
        required: true
        options:
          - { label: 'רמה 1', value: 'bw_lev_1' }
          - { label: 'רמה 2', value: 'bw_lev_2' }
          - { label: 'רמה 3', value: 'bw_lev_3' }
          - { label: 'רמה 4', value: 'bw_lev_4' }
          - { label: 'רמה 5', value: 'bw_lev_5' }

